from operator import add
import random

# Basic iter function

l = [1, 2, 3]
# i = iter(l)
# print(next(i))
# print(next(i))
# print(next(i))
# print(next(i))


# Extended iter function
# iter(callable, val) , val is the value at which iterator will stop if value generated by callable matches val

for _ in iter(lambda: random.randint(1, 10), 5):
    print(_)
