"""empty message

Revision ID: 59fb59d2d7f5
Revises: 
Create Date: 2019-01-03 15:39:28.911308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fb59d2d7f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('actor.id', sa.Integer(), nullable=True),
    sa.Column('movie.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor.id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie.id'], ['movie.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('movie')
    op.drop_table('actor')
    # ### end Alembic commands ###
